### ISSUE TITLE
Pluralsight AngularJS Patterns: Clean Code

### ISSUE THREAD

**Issue by MAustinMMDP** [johnpapa/ng-demos#56]
I am attempting to follow your tutorial on Pluralsight and I am not getting the same results. I have cloned the repo and installed the modular project. I started gulp serve-dev and nothing loads on port 7200. Port 7203 does display the dark gray background with the title "ANGULAR MODULE DEMO", however, the application does not load. The console shows that resources are being loaded, e.g., GET, just not sure where to. 

It appears changes have been made to the source code since the tutorial was made so they don't jive. I did notice the var port in app.js differs from the var port in the gulpfile.js; app.js var port = process.env.PORT || 7200 and gulpfile.js references 7203. Not sure if this is the problem as I am just getting familiar with the project configuration and it was something I noticed. I am on a trial subscription which ends on June 3rd so if you could help ... the sooner the better. 

Thanks!

**Comment by zxxz** [comment]
Hello there,
If you start the application from the command line with ```gulp serve-dev```, you have to go to [http://localhost:7203](http://localhost:7203). 
If you follow the tutorial and create a Run configuration (Node) pointing to the ```app.js```, you have to go to [http://localhost:7200](http://localhost:7200).
But I suspect your problem is elsewhere. 
From the command line, make sure you are in the ```modular``` folder and run ```npm install```: look at the output and make sure there are no errors.
If you are on a Mac, you might have some permissions issues that cause ```npm install``` to fail. 
If that's the case, you might want to look at the following issue: https://github.com/johnpapa/ng-demos/issues/41#issuecomment-71908068 and read until the end.

**Comment by MAustinMMDP** [comment]
Thanks! I got it running. I had initially installed the app in the Windows Command Prompt with Admin rights but when it failed to install browser-sync I opened the project in Webstorm and completed the install of the missing packages in the Terminal. Doing it this way skipped the bower install. I did one more npm install and it was able to finish successfully.

**Comment by johnpapa** [comment]
cool, thanks

**Comment by faisq4** [comment]
Hi John,

Can I get code sample for this PluralSight course, as When I try to download it through the link being provided in the course, it is expired.
